blank_issues_enabled: false
contact_links:
  - name: Slack [for Reckonsys Employees]
    url: https://reckonsystech.slack.com/archives/C0126BVSGBF
    about: Reckonsys Internal slack pythonista channel
